'#ff0000' = 'spleen'
'#00ffff' = 'CSF'
'#ffe680' = 'adipose'
'#ffff44' = 'bonemarrow'
'#800000' = 'liver'
'#008000' = 'muscle'
'#aa4400' = 'kidneyMed'
'#552200' = 'kidneyCor'
'#ffff00' = 'spinalCord'
'#808000' = 'cortical'
'#ffeeee' = 'blood'
'#1a2020' = 'stomach'
'#ff8080' = 'perotineum'